NAME = "generic"
DESCRIPTION = "General CadQuery code generation — used when no specific skill matches"
PARAMETERS = {
    "user_request": {"type": "str", "default": ""},
}

# No template — code is fully generated by Gemini for this skill
TEMPLATE = None


def render(params: dict) -> str:
    # Generic skill has no template — returns empty string
    # The agent will use Gemini to generate code directly
    return ""
