from state import AgentState
from llm import call_llm
from skill_loader import load_skill

GENERIC_SYSTEM = """You are a CadQuery code generator and expert.

You have already analyzed the geometry and know exactly what to build.
Write precise, working CadQuery Python code directly — you know the CadQuery API well.

CadQuery API quick reference (for syntax accuracy):
- cq.Workplane("XY").box(l, w, h)
- .circle(r).extrude(h) / .rect(w,h).extrude(h)
- .sphere(radius) / .wedge(dx,dy,dz,xmin,zmin,xmax,zmax)
- .faces(">Z").workplane().hole(d)
- .faces(">Z").workplane().cboreHole(d, cboreD, cboreDepth)
- .faces(">Z").workplane().cskHole(d, cskD, cskAngle)
- .faces(">Z").workplane().rarray(xSpacing,ySpacing,xCount,yCount).hole(d)
- .faces(">Z").workplane().polarArray(radius,start,stop,count).hole(d)
- .edges("|Z").fillet(r) / .edges("|Z").chamfer(l)
- .faces(">Z").shell(-thickness)
- .workplane(offset=h).rect/circle(...).loft()
- .polyline([...]).close().extrude(h)
- .revolve(angle) / .sweep(path) / .twistExtrude(d, angle)
- .text("txt", fontsize, distance)
- .union(other) / .cut(other) / .intersect(other)
- .translate((x,y,z)) / .rotate(...) / .mirror(...)
- cq_warehouse.fastener: HexHeadScrew, HexNut, PlainWasher (size="M8-1.25", fastener_type="iso4017")

Rules:
- ALWAYS start with: import cadquery as cq
- Store final shape in variable called `result`
- ALWAYS end with: show_object(result)
- Output ONLY raw Python code — no markdown, no backticks, no explanation
"""


def code_generation_node(state: AgentState, api_key: str, model: str) -> AgentState:
    print("[3/4] Generating code...")

    # Only try skill template for high-value, error-prone operations
    if state.selected_skill and state.selected_skill != "generic":
        try:
            skill = load_skill(state.selected_skill)
            code  = skill.render(state.extracted_params)
            if code.strip():
                state.generated_code = code
                print(f"  ✓ Code from skill template: {state.selected_skill}")
                return state
        except Exception as e:
            print(f"  Skill render failed ({e}), using Gemini")

    # Default: Gemini generates directly with API reference grounding
    user = (
        f"User request: {state.user_request}\n\n"
        f"Geometric analysis:\n{state.plan}\n\n"
        f"Write the complete CadQuery Python script."
    )

    code = call_llm(api_key, model, GENERIC_SYSTEM, user, state.image_path)

    if code.startswith("```"):
        lines = code.splitlines()
        lines = [l for l in lines if not l.startswith("```")]
        code = "\n".join(lines).strip()

    state.generated_code = code
    print("  ✓ Code generated by Gemini")
    return state
